global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx-app'
    static_configs:
      - targets: ['app:80']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']